### ISSUE TITLE
Change label eikon 1.0.2 from prerelease to main

### ISSUE THREAD

**Issue by wiphoo** [conda-forge/eikon-feedstock#5]
Issue: change eikon 1.0.2 package label from 'prerelease' to 'main'

Hi @conda-forge/core,

Please move my eikon 1.0.2 package from ``prerelease`` to ``main`` on the conda-forge channel on anaconda.org
because: I forgot to rerender and the package label as 'prerelease'. This package should be labeled 'main'. I tried to re-render it to be in main label and it doesn't work with the same build number.

**Comment by CJ-Wright** [comment]
Can you bump the build number and rerender?

**Comment by wiphoo** [comment]
> Can you bump the build number and rerender?

Yes, I can if Conda-Forge prefer that way. 
Thanks
